name: CI/CD Pipeline Carillon

# Déclenchement automatique au push sur main
on:
  push:
    branches: [ "main" ]

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Récupération du code (Checkout)
      uses: actions/checkout@v5

    - name: ⚙️ Configuration de Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22.x' 

    - name: 📦 Installation & Tests (Back-End)
      run: |
        cd server
        npm install
        npm test

    - name: 🚀 Déploiement automatisé sur le VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /home/ksyv/Carillon
          git pull origin main
          cd client && npm install && npm run build
          cd ../server && npm install
          pm2 restart carillon